name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - "sdk/nodejs/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish to npm
        if: success()
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: comnoco/create-release@v2
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nodejs-server-v${{ steps.package-version.outputs.version }}
          release_name: Node.js Server v${{ steps.package-version.outputs.version }}
          body: |
            Release of Node.js SDK version ${{ steps.package-version.outputs.version }}

            This release includes the latest updates to the ContactsManager Node.js server SDK.
          draft: false
          prerelease: false
