name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - ".github/release/RELEASE"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish to npm
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: pipe-cd/actions-gh-release@v2.6.0
        with:
          release_file: ".github/release/RELEASE"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push version changes to GitHub
        run: |
          if [[ -n $(git status -s) ]]; then
            git add package.json .github/release/RELEASE
            git commit -m "Bump version to ${{ steps.package-version.outputs.version }}"
            git push origin main
          fi
